# This is a basic workflow to help you get started with Actions

name: test

# Controls when the workflow will run
on:
  push:
    branches: [ "master"]

    

env:
  # Variables needed to build and push the image
  WORKING_DIC: test
  GHP_IMAGE_NAME: test
  ACR_NAME: https://adessotr.azurecr.io






# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on:
      - ubuntu-latest

    outputs:
      IMAGE_NAME: ${{ steps.setup.outputs.IMAGE_NAME }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of SonarQube reporting
          fetch-depth: 0
 
      # set up image name
      
      # login to GitHub Packages
      - name: Login to Github Packages
        uses: docker/login-action@v1.10.0
        with:
          registry: ${{ env.ACR_NAME }}
          username: adessotr
          password: x44ZmwrVuyaYEhVj+0zsgB=hb9mq88V=
      # Set up Docker environment
      - name: set up qemu
        uses: docker/setup-qemu-action@v1
      - name: set up Docker context for buildx
        id: buildx-context
        run: |
          docker context create builders
      - uses: docker/setup-buildx-action@v1.6.0
        id: buildx
        with:
          version: latest
          endpoint: builders
